feat: allow to style BPMN Elements
process-analytics/bpmn-visualization-R pull request #247
Opened 2023-09-12 14:49 UTC by csouchet

### To build the documentation
- https://cran.r-project.org/web/packages/roxygen2/vignettes/reuse.html
- https://process-analytics.github.io/bpmn-visualization-js/api/interfaces/StyleRegistry.html#updateStyle
- https://process-analytics.github.io/bpmn-visualization-js/api/types/Fill.html
- https://process-analytics.github.io/bpmn-visualization-js/api/types/Stroke.html
- https://process-analytics.github.io/bpmn-visualization-js/api/types/Font.html
- https://process-analytics.github.io/bpmn-visualization-js/api/types/StyleWithOpacity.html

Closes #13

2023-09-13 11:45 UTC, tbouffard requested changes
✔️ Implementation
✔️ Great documentation (including documentation section reuse) 
✔️ A lot of new tests
❌ README
- missing API usage in the README of the repository to be consistent with all existing features that are referenced there
- Consider updating the illustration image: use script of  #72 and #45 (we should put the script in the doc folder instead of keeping it in comments of Pull Requests and probably rename this folder into docs for consistency with other repositories)

--------

⚠️ **Side note about the PR description**: IHMO, there is no need for such a PR description when I am a reviewer. I think it was written by a ChatBot as it is very wordy and doesn't provide the information I expect to find to guide my review and write the merge commit.
- It is mainly a list of added/updated functions and the code and R documentation should be enough to provide the same information. If not, this means that the code and/or the documentation are uncleared
- it only states what is done where I expect to find explanations about why it is done. The code should be clear enough about the what (and if required, add code comments). I would prefer to have a clear text about the "doc section" reuse that is currently hidden in the list of links of the "to build the documentation" paragraph.

I've recently realized that this is becoming the norm in the latest PRs you've opened, and I suggest that it be adapted to help my review. Let's discuss it in person to find a solution that works for both of us.

2023-09-13 11:45 UTC, tbouffard commented on inst/htmlwidgets/bpmnVisualizationR.js
>                          const elementsByIds = bpmnVisualization.bpmnElementsRegistry.getElementsByIds(elementId);
If we agree on this, I can create a dedicated PR to manage the changes

2023-09-13 12:25 UTC, csouchet commented on inst/htmlwidgets/bpmnVisualizationR.js
>                          const elementsByIds = bpmnVisualization.bpmnElementsRegistry.getElementsByIds(elementId);
It's ok for me :slightly\_smiling\_face:

2023-09-13 12:36 UTC, csouchet commented on R/funs.R
> +
```suggestion

```

2023-09-13 15:28 UTC, tbouffard approved these changes
LGTM
ℹ️ the image in the Readme could still be updated

2023-09-14 04:38 UTC, tbouffard commented on inst/htmlwidgets/bpmnVisualizationR.js
>                          const elementsByIds = bpmnVisualization.bpmnElementsRegistry.getElementsByIds(elementId);
Done in #248

2023-09-15 13:49 UTC, csouchet commented on doc/example_email_voting_with_overlays.svg
I didn't use any script. I just edit the svg image.

2023-09-15 13:52 UTC, csouchet commented on doc/example_email_voting_with_overlays.svg
I didn't understand which activity that you mention. The label is centered: 

![](https://github.com/process-analytics/bpmn-visualization-R/assets/4921914/dfa7c406-2091-4da0-a2d6-149d0cda6a82)

2023-09-15 14:55 UTC, tbouffard commented on doc/example_email_voting_with_overlays.svg
Here is how it is rendered in my browser
![image](https://github.com/process-analytics/bpmn-visualization-R/assets/27200110/146240ce-4add-4e1d-bd24-e04013385c42)

We however needs the script that is doing this rendering anyway to be able to reproduce it.
I understand the pain about the label repositioning. Be aware of https://github.com/process-analytics/bpmn-visualization-tools/tree/v0.4.0/bpmn-visualization-svg-screenshots for the next time

2023-09-18 09:40 UTC, tbouffard commented on doc/example_email_voting_with_overlays.svg
As per decision with @csouchet this will be handle with #251 and #252

2023-09-18 09:43 UTC, merged